In [155]:
from sklearn import datasets
iris = datasets.load_iris()

X = iris.data
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [156]:
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [157]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
X = scaler_x.fit_transform(X)
X

array([[-9.00681170e-01,  1.01900435e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00, -1.31979479e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.38535265e+00,  3.28414053e-01, -1.39706395e+00,
        -1.31544430e+00],
       [-1.50652052e+00,  9.82172869e-02, -1.28338910e+00,
        -1.31544430e+00],
       [-1.02184904e+00,  1.24920112e+00, -1.34022653e+00,
        -1.31544430e+00],
       [-5.37177559e-01,  1.93979142e+00, -1.16971425e+00,
        -1.05217993e+00],
       [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
        -1.18381211e+00],
       [-1.02184904e+00,  7.88807586e-01, -1.28338910e+00,
        -1.31544430e+00],
       [-1.74885626e+00, -3.62176246e-01, -1.34022653e+00,
        -1.31544430e+00],
       [-1.14301691e+00,  9.82172869e-02, -1.28338910e+00,
        -1.44707648e+00],
       [-5.37177559e-01,  1.47939788e+00, -1.28338910e+00,
        -1.31544430e+00],
       [-1.26418478e+00,  7.88807586e-01, -1.22655167e+00,
      

In [158]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(categories='auto', sparse=False)
y.shape

(150,)

In [159]:
y = y.reshape(-1, 1)
y.shape

(150, 1)

In [160]:
y = onehot.fit_transform(y)
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [161]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [162]:
X_treinamento.shape

(105, 4)

In [163]:
X_teste.shape

(45, 4)

In [164]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [165]:
import numpy as np

In [166]:
neuronios_entrada = X.shape[1]

In [167]:
neuronios_entrada

4

In [168]:
neuronios_oculta = int(np.ceil((X.shape[1] + y.shape[1]) / 2))
neuronios_oculta

4

In [169]:
neuronios_saida = y.shape[1]
neuronios_saida

3

In [170]:
W = {'oculta': tf.Variable(tf.random_normal([neuronios_entrada, neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_oculta, neuronios_saida]))}
W

{'oculta': <tf.Variable 'Variable_18:0' shape=(4, 4) dtype=float32_ref>,
 'saida': <tf.Variable 'Variable_19:0' shape=(4, 3) dtype=float32_ref>}

In [171]:
b = {'oculta': tf.Variable(tf.random_normal([neuronios_oculta])),
     'saida': tf.Variable(tf.random_normal([neuronios_saida]))}

In [172]:
xph = tf.placeholder('float', [None, neuronios_entrada])
yph = tf.placeholder('float', [None, neuronios_saida])

In [173]:
def mlp(x, W, bias):
    camada_oculta = tf.add(tf.matmul(x, W['oculta']), bias['oculta'])
    camada_oculta_ativacao = tf.nn.relu(camada_oculta)
    camada_saida = tf.add(tf.matmul(camada_oculta_ativacao, W['saida']), b['saida'])
    return camada_saida

In [174]:
modelo = mlp(xph, W, b)

In [175]:
erro = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits = modelo, labels = yph))
otimizador = tf.train.AdamOptimizer(learning_rate=0.0001).minimize(erro)

In [176]:
batch_size = 8
batch_total = int(len(X_treinamento) / batch_size)
batch_total

13

In [177]:
X_batches = np.array_split(X_treinamento, batch_total)
X_batches

[array([[-9.00681170e-01,  1.70959465e+00, -1.22655167e+00,
         -1.31544430e+00],
        [ 3.10997534e-01, -1.31979479e-01,  4.78571135e-01,
          2.64141916e-01],
        [ 4.32165405e-01, -5.92373012e-01,  5.92245988e-01,
          7.90670654e-01],
        [-1.26418478e+00, -1.31979479e-01, -1.34022653e+00,
         -1.44707648e+00],
        [ 1.28034050e+00,  9.82172869e-02,  9.33270550e-01,
          1.18556721e+00],
        [-1.14301691e+00,  1.24920112e+00, -1.34022653e+00,
         -1.44707648e+00],
        [-4.16009689e-01, -1.05276654e+00,  3.64896281e-01,
          8.77547895e-04],
        [ 1.03800476e+00,  9.82172869e-02,  1.04694540e+00,
          1.58046376e+00],
        [ 1.28034050e+00,  3.28414053e-01,  1.10378283e+00,
          1.44883158e+00]]),
 array([[-1.50652052e+00,  3.28414053e-01, -1.34022653e+00,
         -1.31544430e+00],
        [-1.50652052e+00,  7.88807586e-01, -1.34022653e+00,
         -1.18381211e+00],
        [ 1.89829664e-01,  7.88807586e-01

In [178]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoca in range(3000):
        erro_medio = 0.0
        batch_total = int(len(X_treinamento) / batch_size)
        X_batches = np.array_split(X_treinamento, batch_total)
        y_batches = np.array_split(y_treinamento, batch_total)    
        for i in range(batch_total):
            X_batch, y_batch = X_batches[i], y_batches[i]
            _, custo = sess.run([otimizador, erro], feed_dict = {xph: X_batch, yph: y_batch})
            erro_medio += custo / batch_total
            
        if epoca % 500 == 0:
            print('Época: ' + str((epoca + 1)) + '\n Erro: ' + str(erro_medio))
        
    W_final, b_final = sess.run([W, b])

Época: 1
 Erro: 4.649333577889663
Época: 501
 Erro: 0.5307469574304727
Época: 1001
 Erro: 0.25562227689302885
Época: 1501
 Erro: 0.15503840778882685
Época: 2001
 Erro: 0.1007234537257598
Época: 2501
 Erro: 0.07734021705646928


In [179]:
W_final

{'oculta': array([[-0.48684996, -2.021674  ,  0.00467   ,  0.18746528],
        [ 0.3148791 ,  1.9121042 ,  0.17618991,  0.4069102 ],
        [ 1.138506  , -0.9696489 ,  1.9039961 , -0.9433283 ],
        [-0.2053693 , -1.9303178 ,  1.826179  , -0.71901953]],
       dtype=float32),
 'saida': array([[-0.90992975, -0.0920644 , -0.77753896],
        [ 2.766688  , -1.5882483 , -0.8373213 ],
        [-2.8519826 , -0.82873917,  1.1626282 ],
        [-1.566468  ,  1.9777372 , -1.5571159 ]], dtype=float32)}

In [180]:
b_final

{'oculta': array([-1.0787953 ,  0.08577589, -0.13710935,  1.8180071 ], dtype=float32),
 'saida': array([-1.7679367 ,  1.3644055 , -0.31945375], dtype=float32)}

In [181]:
# previsoes
previsoes_teste = mlp(xph, W_final, b_final)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    r1 = sess.run(previsoes_teste, feed_dict = {xph: X_teste})
    r2 = sess.run(tf.nn.softmax(r1))
    r3 = sess.run(tf.argmax(r2, 1))

In [182]:
r1

array([[-9.90790653e+00, -1.72675848e-02,  3.22114849e+00],
       [-5.20043373e+00,  2.91088676e+00, -1.05985597e-01],
       [-3.75090814e+00,  4.16404533e+00, -1.44772172e+00],
       [ 1.73657761e+01, -3.12603951e+00, -1.42037582e+01],
       [-1.29071541e+01, -1.09471738e+00,  4.62964869e+00],
       [ 1.96874275e+01, -4.39214230e+00, -1.50319510e+01],
       [-5.37223244e+00,  2.91411400e+00, -8.39173347e-02],
       [ 1.44822512e+01, -2.23264885e+00, -1.18960762e+01],
       [ 1.08471823e+01, -8.12336206e-02, -1.09177303e+01],
       [-2.13219285e+00,  4.90927267e+00, -2.35565543e+00],
       [ 1.58872786e+01, -2.84599400e+00, -1.26852169e+01],
       [ 1.03868732e+01,  4.47610974e-01, -1.12767611e+01],
       [-2.85323048e+00,  4.18157721e+00, -1.59407258e+00],
       [-1.37620592e+01, -2.06785440e+00,  5.63220596e+00],
       [ 1.39896955e+01, -1.91552436e+00, -1.18117342e+01],
       [ 1.65370808e+01, -2.98369122e+00, -1.33250914e+01],
       [ 1.47095079e+01, -1.52663195e+00

In [183]:
r2

array([[1.91167032e-06, 3.77453007e-02, 9.62252796e-01],
       [2.86033901e-04, 9.53057826e-01, 4.66560759e-02],
       [3.63778614e-04, 9.95996237e-01, 3.63997440e-03],
       [1.00000000e+00, 1.26042665e-09, 1.94771516e-14],
       [2.41239064e-08, 3.25479382e-03, 9.96745110e-01],
       [1.00000000e+00, 3.48638445e-11, 8.34766693e-16],
       [2.39905101e-04, 9.52256680e-01, 4.75034937e-02],
       [1.00000000e+00, 5.50567734e-08, 3.49976103e-12],
       [9.99981999e-01, 1.79407780e-05, 3.52867097e-10],
       [8.73468060e-04, 9.98427987e-01, 6.98551885e-04],
       [1.00000000e+00, 7.31548466e-09, 3.90052709e-13],
       [9.99951720e-01, 4.82405485e-05, 3.90464716e-10],
       [8.77193699e-04, 9.96032894e-01, 3.08987382e-03],
       [3.77556120e-09, 4.52594919e-04, 9.99547422e-01],
       [9.99999881e-01, 1.23723055e-07, 6.23133880e-12],
       [1.00000000e+00, 3.32841044e-09, 1.07404835e-13],
       [9.99999881e-01, 8.88657183e-08, 5.38622369e-13],
       [1.29064174e-05, 3.47121

In [184]:
r3

array([2, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0,
       1, 1, 1, 1, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0,
       2])

In [185]:
y_teste2 = np.argmax(y_teste, 1)
y_teste2

array([2, 1, 1, 0, 2, 0, 1, 0, 0, 1, 0, 0, 1, 2, 0, 0, 0, 2, 2, 0, 2, 0,
       1, 1, 1, 1, 0, 2, 2, 2, 1, 1, 0, 0, 2, 0, 0, 0, 0, 2, 2, 0, 0, 0,
       2])

In [186]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste2, r3)
taxa_acerto

1.0