# Rede Neural Operador E
Podemos usar o operador `or` também para a Rede Neural abaixo

In [54]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np

In [55]:
X = np.array([[0.0, 0.0],
              [0.0, 1.0],
              [1.0, 0.0],
              [1.0, 1.0]])
X

array([[0., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.]])

In [56]:
y = np.array([[0.0], [0.0], [0.0], [1.0]])
y

array([[0.],
       [0.],
       [0.],
       [1.]])

In [57]:
W = tf.Variable(tf.zeros([2, 1], dtype = tf.float64))
type(W)

tensorflow.python.ops.variables.RefVariable

In [58]:
def step(x):
    return tf.cast(tf.to_float(tf.math.greater_equal(x, 1)), tf.float64)

In [59]:
print(W)

<tf.Variable 'Variable_2:0' shape=(2, 1) dtype=float64_ref>


In [60]:
init = tf.global_variables_initializer()

In [61]:
camada_saida = tf.matmul(X, W)

In [62]:
camada_saida_ativacao = step(camada_saida)

In [63]:
erro = tf.subtract(y, camada_saida_ativacao)

In [64]:
delta = tf.matmul(X, erro, transpose_a = True)
treinamento = tf.assign(W, tf.add(W, tf.multiply(delta, 0.1)))

In [65]:
with tf.Session() as sess:
    sess.run(init)
    # print(sess.run(W))
    # print(sess.run(camada_saida))
    
    # print(sess.run(step(1)))
    # print('\n')
    # print(sess.run(camada_saida_ativacao))
    # print(X)
    # print(sess.run(erro))
    # print(sess.run(tf.transpose(X)))
    # print(sess.run(treinamento))
    epoca = 0
    for i in range(15):
        epoca += 1
        erro_total, _ = sess.run([erro, treinamento])
        erro_soma = tf.reduce_sum(erro_total)
        # print(erro_total)
        print('Época: ', epoca, ' Erro: ', sess.run(erro_soma))
        if erro_soma.eval() == 0.0:
            break
            
    W_final = sess.run(W)

Época:  1  Erro:  1.0
Época:  2  Erro:  1.0
Época:  3  Erro:  1.0
Época:  4  Erro:  1.0
Época:  5  Erro:  1.0
Época:  6  Erro:  0.0


In [66]:
print(W_final)

[[0.5]
 [0.5]]


In [67]:
# teste
camada_saida_teste = tf.matmul(X, W_final)
camada_saida_ativacao_teste = step(camada_saida_teste)
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(camada_saida_ativacao_teste))

[[0.]
 [0.]
 [0.]
 [1.]]
