In [92]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [93]:
base.shape

(21613, 21)

In [94]:
X = base.iloc[:, 5:6].values
y = base.iloc[:, 2:3].values

In [95]:
X

array([[1180],
       [2570],
       [ 770],
       ...,
       [1020],
       [1600],
       [1020]])

In [96]:
y

array([[221900.],
       [538000.],
       [180000.],
       ...,
       [402101.],
       [400000.],
       [325000.]])

In [97]:
from sklearn.preprocessing import StandardScaler
scale_x = StandardScaler()
X = scale_x.fit_transform(X)
scale_y = StandardScaler()
y = scale_y.fit_transform(y)

In [98]:
X

array([[-0.97983502],
       [ 0.53363434],
       [-1.42625404],
       ...,
       [-1.15404732],
       [-0.52252773],
       [-1.15404732]])

In [99]:
y

array([[-0.86671733],
       [-0.00568792],
       [-0.98084935],
       ...,
       [-0.37586519],
       [-0.38158814],
       [-0.58588173]])

In [100]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [101]:
colunas = [tf.feature_column.numeric_column('x', shape = [1])]
colunas

[NumericColumn(key='x', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [102]:
regressor = tf.estimator.LinearRegressor(feature_columns = colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmppk0p84r3', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fc6eea502b0>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [103]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [104]:
X_treinamento.shape

(15129, 1)

In [105]:
y_treinamento.shape

(15129, 1)

In [106]:
X_teste.shape

(6484, 1)

In [107]:
y_teste.shape

(6484, 1)

In [108]:
funcao_treinamento = tf.estimator.inputs.numpy_input_fn({'x': X_treinamento}, y_treinamento, 
                                                        batch_size=32, num_epochs= None, 
                                                        shuffle= True)

In [109]:
funcao_teste = tf.estimator.inputs.numpy_input_fn({'x': X_teste}, y_teste, 
                                                  batch_size=32, num_epochs=1000, shuffle = False)

In [110]:
regressor.train(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmppk0p84r3/model.ckpt.
INFO:tensorflow:loss = 13.895179, step = 1
INFO:tensorflow:global_step/sec: 518.818
INFO:tensorflow:loss = 6.5598783, step = 101 (0.193 sec)
INFO:tensorflow:global_step/sec: 673.668
INFO:tensorflow:loss = 8.281682, step = 201 (0.149 sec)
INFO:tensorflow:global_step/sec: 468.415
INFO:tensorflow:loss = 9.685842, step = 301 (0.214 sec)
INFO:tensorflow:global_step/sec: 682.017
INFO:tensorflow:loss = 6.0574465, step = 401 (0.146 sec)
INFO:tensorflow:global_step/sec: 936.31
INFO:tensorflow:loss = 5.9893, step = 501 (0.109 sec)
INFO:tensorflow:global_step/sec: 828.123
INFO:tensorflow:loss = 13.111425, step = 601 (0.118 sec)
INFO:tensorflow:glo

INFO:tensorflow:loss = 21.872547, step = 8001 (0.113 sec)
INFO:tensorflow:global_step/sec: 937.497
INFO:tensorflow:loss = 16.131353, step = 8101 (0.107 sec)
INFO:tensorflow:global_step/sec: 820.601
INFO:tensorflow:loss = 12.429132, step = 8201 (0.122 sec)
INFO:tensorflow:global_step/sec: 1030.63
INFO:tensorflow:loss = 6.1460524, step = 8301 (0.097 sec)
INFO:tensorflow:global_step/sec: 920.753
INFO:tensorflow:loss = 17.721008, step = 8401 (0.109 sec)
INFO:tensorflow:global_step/sec: 805.605
INFO:tensorflow:loss = 34.503036, step = 8501 (0.124 sec)
INFO:tensorflow:global_step/sec: 927.722
INFO:tensorflow:loss = 11.251563, step = 8601 (0.108 sec)
INFO:tensorflow:global_step/sec: 773.79
INFO:tensorflow:loss = 16.997303, step = 8701 (0.129 sec)
INFO:tensorflow:global_step/sec: 865.456
INFO:tensorflow:loss = 9.8425045, step = 8801 (0.116 sec)
INFO:tensorflow:global_step/sec: 1003.11
INFO:tensorflow:loss = 11.578918, step = 8901 (0.100 sec)
INFO:tensorflow:global_step/sec: 881.384
INFO:tensor

In [111]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-20T13:20:04Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmppk0p84r3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-07-20-13:20:12
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.51644075, global_step = 10000, label/mean = 0.0025011578, loss = 16.526104, prediction/mean = -0.00

In [112]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-20T13:20:13Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmppk0p84r3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-07-20-13:20:23
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.48569232, global_step = 10000, label/mean = -0.0056905486, loss = 15.542154, prediction/mean = 0.00

In [113]:
metricas_treinamento

{'average_loss': 0.51644075,
 'label/mean': 0.0025011578,
 'loss': 16.526104,
 'prediction/mean': -0.00034979568,
 'global_step': 10000}

In [114]:
metricas_teste

{'average_loss': 0.48569232,
 'label/mean': -0.0056905486,
 'loss': 15.542154,
 'prediction/mean': 0.009124897,
 'global_step': 10000}

In [115]:
import numpy as np
novas_casas = np.array([[800], [900], [1000]])
novas_casas

array([[ 800],
       [ 900],
       [1000]])

In [116]:
novas_casas = scale_x.transform(novas_casas)
novas_casas

array([[-1.39358923],
       [-1.28470655],
       [-1.17582386]])

In [117]:
funcao_previsao = tf.estimator.inputs.numpy_input_fn({'x': novas_casas}, shuffle = False)

In [118]:
previsoes = regressor.predict(input_fn=funcao_previsao)
previsoes

<generator object Estimator.predict at 0x7fc70a040eb8>

In [119]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmppk0p84r3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([-0.9715262], dtype=float32)},
 {'predictions': array([-0.8954335], dtype=float32)},
 {'predictions': array([-0.8193407], dtype=float32)}]

In [121]:
for p in regressor.predict(input_fn=funcao_previsao):
#     print(p['predictions'])
    print(scale_y.inverse_transform(p['predictions']))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmppk0p84r3/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
[183422.7]
[211357.77]
[239292.83]
