In [1]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [2]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [3]:
colunas_usadas = ['price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']

In [4]:
colunas_usadas

['price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [5]:
base = pd.read_csv('house_prices.csv', usecols=colunas_usadas)

In [6]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

   zipcode      lat     long  
0    98178  47.5112 -122.257  
1    98125  47.7210 -122.319  
2    98028  47.7379 -122.233  
3    98136  47.5208 -122.393  
4    98074  47.6168 -122.045

In [7]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long']])

In [8]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  538000.0  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  180000.0  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  604000.0  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  510000.0  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [9]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [10]:
base.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  0.019266  0.090909    0.12500     0.067170  0.003108     0.0         0.0   
1  0.060721  0.090909    0.28125     0.172075  0.004072     0.4         0.0   
2  0.013770  0.060606    0.12500     0.036226  0.005743     0.0         0.0   
3  0.069377  0.121212    0.37500     0.126038  0.002714     0.0         0.0   
4  0.057049  0.090909    0.25000     0.104906  0.004579     0.0         0.0   

   view  condition     grade  sqft_above  sqft_basement  yr_built  \
0   0.0        0.5  0.500000    0.097588       0.000000  0.478261   
1   0.0        0.5  0.500000    0.206140       0.082988  0.443478   
2   0.0        0.5  0.416667    0.052632       0.000000  0.286957   
3   0.0        1.0  0.500000    0.083333       0.188797  0.565217   
4   0.0        0.5  0.583333    0.152412       0.000000  0.756522   

   yr_renovated   zipcode       lat      long  
0      0.000000  0.893939  0.571498  0.217608  
1      0.988089  0.626263  0.908959  0.166113  
2      0.000000  0.136364  0.936143  0.237542  
3      0.000000  0.681818  0.586939  0.104651  
4      0.000000  0.368687  0.741354  0.393688

In [13]:
X = base.drop('price', axis = 1)
y = base.price

In [16]:
X.head()

bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
0  0.090909    0.12500     0.067170  0.003108     0.0         0.0   0.0   
1  0.090909    0.28125     0.172075  0.004072     0.4         0.0   0.0   
2  0.060606    0.12500     0.036226  0.005743     0.0         0.0   0.0   
3  0.121212    0.37500     0.126038  0.002714     0.0         0.0   0.0   
4  0.090909    0.25000     0.104906  0.004579     0.0         0.0   0.0   

   condition     grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0        0.5  0.500000    0.097588       0.000000  0.478261      0.000000   
1        0.5  0.500000    0.206140       0.082988  0.443478      0.988089   
2        0.5  0.416667    0.052632       0.000000  0.286957      0.000000   
3        1.0  0.500000    0.083333       0.188797  0.565217      0.000000   
4        0.5  0.583333    0.152412       0.000000  0.756522      0.000000   

    zipcode       lat      long  
0  0.893939  0.571498  0.217608  
1  0.626263  0.908959  0.166113  
2  0.136364  0.936143  0.237542  
3  0.681818  0.586939  0.104651  
4  0.368687  0.741354  0.393688

In [18]:
type(X)

pandas.core.frame.DataFrame

In [19]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

In [20]:
type(y)

pandas.core.series.Series

In [21]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [23]:
previsores_colunas = colunas_usadas[1:17]
previsores_colunas

['bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long']

In [24]:
colunas = [tf.feature_column.numeric_column(key = c) for c in previsores_colunas]

In [27]:
print(colunas[10])

NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)


In [28]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [29]:
X_treinamento.shape

(15129, 16)

In [30]:
y_treinamento.shape

(15129,)

In [31]:
X_teste.shape

(6484, 16)

In [32]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = X_treinamento, y = y_treinamento,
                                                        batch_size= 32, num_epochs=None, shuffle= True)
funcao_teste = tf.estimator.inputs.pandas_input_fn(x = X_teste, y = y_teste,
                                                        batch_size= 32, num_epochs=1000, shuffle= False)

In [33]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmpzr6rbg75', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fa423a0d240>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [34]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

Instructions for updating:
Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Use `tf.cast` instead.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmpzr6rbg75/model.ckpt.
INFO:tensorflow:loss = 0.20243697, step 

INFO:tensorflow:loss = 0.012019576, step = 3801 (0.434 sec)
INFO:tensorflow:global_step/sec: 230.444
INFO:tensorflow:loss = 0.0076632556, step = 3901 (0.434 sec)
INFO:tensorflow:global_step/sec: 250.383
INFO:tensorflow:loss = 0.016250025, step = 4001 (0.406 sec)
INFO:tensorflow:global_step/sec: 213.574
INFO:tensorflow:loss = 0.021500902, step = 4101 (0.462 sec)
INFO:tensorflow:global_step/sec: 268.44
INFO:tensorflow:loss = 0.13401696, step = 4201 (0.374 sec)
INFO:tensorflow:global_step/sec: 241.245
INFO:tensorflow:loss = 0.035453226, step = 4301 (0.413 sec)
INFO:tensorflow:global_step/sec: 214.863
INFO:tensorflow:loss = 0.00874945, step = 4401 (0.466 sec)
INFO:tensorflow:global_step/sec: 253.649
INFO:tensorflow:loss = 0.020201983, step = 4501 (0.394 sec)
INFO:tensorflow:global_step/sec: 266.625
INFO:tensorflow:loss = 0.12484904, step = 4601 (0.375 sec)
INFO:tensorflow:global_step/sec: 260.077
INFO:tensorflow:loss = 0.012146076, step = 4701 (0.386 sec)
INFO:tensorflow:global_step/sec: 2

In [35]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-20T13:41:09Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmpzr6rbg75/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-07-20-13:41:50
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00066849304, global_step = 10000, label/mean = 0.060885448, loss = 0.021391777, prediction/mean = 0

In [36]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2020-07-20T13:41:55Z
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmpzr6rbg75/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2020-07-20-13:42:38
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00079152634, global_step = 10000, label/mean = 0.06125612, loss = 0.025328843, prediction/mean = 0.

In [37]:
metricas_treinamento

{'average_loss': 0.00066849304,
 'label/mean': 0.060885448,
 'loss': 0.021391777,
 'prediction/mean': 0.060577516,
 'global_step': 10000}

In [38]:
metricas_teste

{'average_loss': 0.00079152634,
 'label/mean': 0.06125612,
 'loss': 0.025328843,
 'prediction/mean': 0.060446434,
 'global_step': 10000}

In [39]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = X_teste, shuffle=False)

In [40]:
previsoes = regressor.predict(input_fn=funcao_previsao)

In [41]:
list(previsoes)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmpzr6rbg75/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


[{'predictions': array([0.07279272], dtype=float32)},
 {'predictions': array([0.05357029], dtype=float32)},
 {'predictions': array([0.10265485], dtype=float32)},
 {'predictions': array([0.0502164], dtype=float32)},
 {'predictions': array([0.05817523], dtype=float32)},
 {'predictions': array([0.02784076], dtype=float32)},
 {'predictions': array([0.05429756], dtype=float32)},
 {'predictions': array([0.11363705], dtype=float32)},
 {'predictions': array([0.0016899], dtype=float32)},
 {'predictions': array([0.08135269], dtype=float32)},
 {'predictions': array([0.11075438], dtype=float32)},
 {'predictions': array([0.09194479], dtype=float32)},
 {'predictions': array([0.0462054], dtype=float32)},
 {'predictions': array([0.25496045], dtype=float32)},
 {'predictions': array([0.04129206], dtype=float32)},
 {'predictions': array([0.04884868], dtype=float32)},
 {'predictions': array([0.03255016], dtype=float32)},
 {'predictions': array([0.04306868], dtype=float32)},
 {'predictions': array([0.09860

In [42]:
valores_previsoes = []
for p in regressor.predict(input_fn=funcao_previsao):
    valores_previsoes.append(p['predictions'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /var/folders/g6/p8gwgl9130db7k9305wfz8340000gn/T/tmpzr6rbg75/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [43]:
valores_previsoes

[array([0.07279272], dtype=float32),
 array([0.05357029], dtype=float32),
 array([0.10265485], dtype=float32),
 array([0.0502164], dtype=float32),
 array([0.05817523], dtype=float32),
 array([0.02784076], dtype=float32),
 array([0.05429756], dtype=float32),
 array([0.11363705], dtype=float32),
 array([0.0016899], dtype=float32),
 array([0.08135269], dtype=float32),
 array([0.11075438], dtype=float32),
 array([0.09194479], dtype=float32),
 array([0.0462054], dtype=float32),
 array([0.25496045], dtype=float32),
 array([0.04129206], dtype=float32),
 array([0.04884868], dtype=float32),
 array([0.03255016], dtype=float32),
 array([0.04306868], dtype=float32),
 array([0.09860694], dtype=float32),
 array([0.03304411], dtype=float32),
 array([0.08911472], dtype=float32),
 array([0.06321896], dtype=float32),
 array([0.03145337], dtype=float32),
 array([0.02533612], dtype=float32),
 array([0.03538764], dtype=float32),
 array([0.03292265], dtype=float32),
 array([0.04741756], dtype=float32),
 arr

In [44]:
import numpy as np
valores_previsoes = np.asarray(valores_previsoes).reshape(-1, 1)

In [45]:
valores_previsoes

array([[0.07279272],
       [0.05357029],
       [0.10265485],
       ...,
       [0.08080765],
       [0.04892511],
       [0.08377845]], dtype=float32)

In [46]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes

array([[630044.44],
       [483473.47],
       [857743.25],
       ...,
       [691158.3 ],
       [448053.97],
       [713810.6 ]], dtype=float32)

In [47]:
y_teste

1482     0.056361
15581    0.042623
15654    0.095075
10912    0.050492
12799    0.064918
           ...   
17990    0.042610
17988    0.030820
6073     0.095082
20599    0.039475
3757     0.072131
Name: price, Length: 6484, dtype: float64

In [48]:
y_teste.shape

(6484,)

In [49]:
y_teste2 = y_teste.values.reshape(-1, 1)
y_teste2.shape

(6484, 1)

In [50]:
y_teste2 = scaler_y.inverse_transform(y_teste2)
y_teste2

array([[504750.],
       [400000.],
       [799950.],
       ...,
       [800000.],
       [376000.],
       [625000.]])

In [52]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_teste2, valores_previsoes)

In [53]:
mae

129015.68026694216